# Generated by Django 4.2.4 on 2023-10-06 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                ("country", models.CharField(max_length=20, verbose_name="страна")),
                ("city", models.CharField(max_length=25, verbose_name="город")),
                ("street", models.CharField(max_length=30, verbose_name="улица")),
                ("house", models.IntegerField(verbose_name="номер дома")),
            ],
            options={
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="название")),
                ("model", models.CharField(max_length=50, verbose_name="модель")),
                (
                    "date_start_sell",
                    models.DateTimeField(verbose_name="дата выхода на рынок"),
                ),
                (
                    "is_start_sell",
                    models.BooleanField(default=False, verbose_name="старт продаж"),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.CreateModel(
            name="Retail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("0", "завод"), ("1", "ИП"), ("2", "розничная сеть")],
                        verbose_name="поставщик",
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="задолженность"
                    ),
                ),
                (
                    "date_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания"
                    ),
                ),
                ("level", models.IntegerField(default=1, verbose_name="уровень")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="factory.contacts",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="factory.products",
                    ),
                ),
            ],
            options={
                "verbose_name": "розничная сеть",
                "verbose_name_plural": "розничные сети",
            },
        ),
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="задолженность клиентов",
                    ),
                ),
                (
                    "date_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания"
                    ),
                ),
                ("level", models.IntegerField(default=0, verbose_name="уровень")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="factory.contacts",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="factory.products",
                    ),
                ),
            ],
            options={
                "verbose_name": "завод",
                "verbose_name_plural": "завод",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("0", "завод"), ("2", "ИП"), ("1", "розничная сеть")],
                        verbose_name="поставщик",
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="задолженность"
                    ),
                ),
                (
                    "date_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания"
                    ),
                ),
                ("level", models.IntegerField(default=1, verbose_name="уровень")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="factory.contacts",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="factory.products",
                    ),
                ),
            ],
            options={
                "verbose_name": "ИП",
                "verbose_name_plural": "ИП",
            },
        ),
    ]
